# Generated by Django 3.2 on 2021-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djanpost', '0002_alter_login_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='sam',
        ),
    ]
